{
 "title": "Kafka broker",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Byte Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\r\rkafka_server_brokertopicmetrics_bytesinpersec_oneminuterate",
     "legendFormat": "Incoming byte rate"
    },
    {
     "expr": "\rkafka_server_brokertopicmetrics_bytesoutpersec_oneminuterate",
     "legendFormat": "Outgoing byte rate"
    }
   ]
  },
  {
   "title": "Produce request rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\r\rkafka_server_brokertopicmetrics_totalproducerequestspersec_oneminuterate",
     "legendFormat": "Produce request rate"
    },
    {
     "expr": "\rkafka_server_brokertopicmetrics_failedproducerequestspersec_oneminuterate",
     "legendFormat": "Failed produce requests"
    },
    {
     "expr": "kafka_network_requestmetrics_totaltimems_produce_count_request",
     "legendFormat": "Produce latency"
    }
   ]
  },
  {
   "title": "Partions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\rkafka_server_replicamanager_partitioncount_value",
     "legendFormat": "Partitions"
    },
    {
     "expr": "\r\rkafka_server_replicamanager_underreplicatedpartitions_value",
     "legendFormat": "Under replicated partitions"
    }
   ]
  },
  {
   "title": "Fetch request rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\r\rkafka_server_brokertopicmetrics_totalfetchrequestspersec_oneminuterate",
     "legendFormat": "Fetch request rate"
    },
    {
     "expr": "kafka_server_brokertopicmetrics_failedfetchrequestspersec_oneminuterate",
     "legendFormat": "Failed fetch requests"
    },
    {
     "expr": "kafka_network_requestmetrics_totaltimems_fetchconsumer_count_request",
     "legendFormat": "Fetch latency"
    }
   ]
  }
 ]
}