{
 "title": "kafka-network",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "broker", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "FetchComsumer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_totaltimems_fetchconsumer_count_request{job=\"$broker\"}",
     "legendFormat": "Total time per request"
    }
   ]
  },
  {
   "title": "FetchFollower",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_totaltimems_fetchfollower_count_request{job=\"$broker\"}",
     "legendFormat": "Total time per request"
    }
   ]
  },
  {
   "title": "Produce",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_totaltimems_produce_count_request{job=\"$broker\"}",
     "legendFormat": "Total time per request"
    }
   ]
  }
 ]
}